FROM nginx:1.27.2
RUN mkdir /usr/share/nginx/html/web/
COPY dist/ /usr/share/nginx/html/web/
COPY dist/index.html /usr/share/nginx/html/index.html
COPY nginx/default-release.conf /etc/nginx/conf.d/default.conf
