export default [
  {
    id: '1',
    taskName: 'Hall Cleaning',
    robotName: 'Alpha 01',
    robotSN: '345567782',
    mapName: '1#0#GateA1-A6',
    location: 'Hall, W, Level4, San Diego Central Library, San Diego, CA, Southwest',
    planArea: '66m² / 125m²',
    startTime: 'Nov. 22, 2024 03:45',
    endTime: 'Nov. 22, 2024 10:06',
    efficiency: '100m²/h',
    remainingTime: '31min',
    consumption: '1.5kWh',
    progress: 60,
    status: 'In Progress',
    duration: '',
    initialPower: '',
    finalPower: '',
    type: '1'
  },
  {
    id: '2',
    taskName: 'Gate Cleaning',
    robotName: 'Alpha 01',
    robotSN: '345567782',
    mapName: '3#0#GateA2-A6',
    location: 'Hall, W, Level4, San Diego Central Library, San Diego, CA, Southwest',
    planArea: '95m² / 95m²',
    startTime: 'Nov. 22, 2024 02:13',
    endTime: 'Nov. 22, 2024 06:16',
    efficiency: '95m²/h',
    remainingTime: '0min',
    consumption: '1.1kWh',
    progress: 100,
    status: 'Done',
    duration: '',
    initialPower: '',
    finalPower: '',
    type: '1'
  },
  {
    id: '3',
    taskName: 'Room01 Cleaning',
    robotName: 'Alpha 02',
    robotSN: '945567790',
    mapName: '3#0#GateA2-A6',
    location: 'Room 01, W, Level4, San Diego Central Library, San Diego, CA, Southwest',
    planArea: '37m² / 74m²',
    startTime: 'Nov. 22, 2024 08:03',
    endTime: 'Nov. 22, 2024 10:26',
    efficiency: '66m²/h',
    remainingTime: '1h 1min',
    consumption: '0.82kWh',
    progress: 50,
    status: 'In Progress',
    duration: '',
    initialPower: '',
    finalPower: '',
    type: '1'
  },
  {
    id: '4',
    taskName: 'Room02 Cleaning',
    robotName: 'Alpha 07',
    robotSN: '244567112',
    mapName: '3#01#RoomA2-A6',
    location: 'Room 02, W, Level4, San Diego Central Library, San Diego, CA, Southwest',
    planArea: '51m² / 112m²',
    startTime: 'Nov. 22, 2024 18:11',
    endTime: 'Nov. 22, 2024 20:30',
    efficiency: '71m²/h',
    remainingTime: '0min',
    consumption: '2.1kWh',
    progress: 46,
    status: 'Uncompleted',
    duration: '',
    initialPower: '',
    finalPower: '',
    type: '1'
  },
  {
    id: '5',
    taskName: 'Room02 Cleaning',
    robotName: 'Beta 01',
    robotSN: '376668255',
    mapName: '0#02#RoomA3-A1',
    location: 'Restroom, W, Level4, San Diego Central Library, San Diego, CA, Southwest',
    planArea: '0m² / 39m²',
    startTime: 'Nov. 23, 2024 11:29',
    endTime: 'Nov. 23, 2024 12:30',
    efficiency: 'NULL',
    remainingTime: '1h 1min',
    consumption: 'NULL',
    progress: 0,
    status: 'Scheduled',
    duration: '',
    initialPower: '',
    finalPower: '',
    type: '1'
  },
  {
    id: '6',
    taskName: '',
    mapName: '',
    planArea: '',
    efficiency: '',
    remainingTime: '',
    consumption: '',
    progress: 0,
    robotName: 'Alpha 07',
    robotSN: '244567112',
    location: 'Room 02, W, Level4, San Diego Central Library, San Diego, CA, Southwest',
    startTime: 'Nov. 23, 2024 09:12',
    endTime: 'Nov. 23, 2024 10:20',
    duration: '1h 8min',
    initialPower: '18%',
    finalPower: '90%',
    status: 'In Progress',
    type: '2'
  },
  {
    id: '7',
    taskName: '',
    mapName: '',
    planArea: '',
    efficiency: '',
    remainingTime: '',
    consumption: '',
    progress: 0,
    robotName: 'Alpha 01',
    robotSN: '345567782',
    location: 'Hall, W, Level4, San Diego Central Library, San Diego, CA, Southwest',
    startTime: 'Nov. 23, 2024 04:00',
    endTime: 'Nov. 23, 2024 05:01',
    duration: '1h 1min',
    initialPower: '30%',
    finalPower: '100%',
    status: 'Done',
    type: '2'
  },
  {
    id: '8',
    taskName: '',
    mapName: '',
    planArea: '',
    efficiency: '',
    remainingTime: '',
    consumption: '',
    progress: 0,
    robotName: 'Alpha 02',
    robotSN: '945567790',
    location: 'Room 01, W, Level4, San Diego Central Library, San Diego, CA, Southwest',
    startTime: 'Nov. 23, 2024 01:13',
    endTime: 'Nov. 23, 2024 02:16',
    duration: '1h 3min',
    initialPower: '18%',
    finalPower: '100%',
    status: 'Done',
    type: '2'
  }
];
